---
title: "Special Factors and Products"
author: "Maribel Espiritu"
format: pptx
editor: visual
---

## SPECIAL PRODUCT {.smaller transition="fade-in fade-out"}

1. Product of a Monomial and a Polynomial
$a(x+y)=ax+ay$

2. Product of the Sum and Difference of Two Terms

$(x+y)(x-y)=x^2-y^2$

3. Square of a Binomial

$(x+y)^2=x^2+2xy+y^2)$ and

$(x-y)^2=x^2-2xy+y^2)$


::: footer
:::

## SPECIAL PRODUCT {.smaller transition="fade-in fade-out"}

4. Product of Two Binomial

$(x+a)(x+b)=x^2+(a+b)x+ab$ and 

$(ax+b)(cx+d)=acx^2+(ad+bc)x+bd$

5. Cube of a Binomial

$(x+y)^3=x^3+3x^2y+3xy^2+y^3$ and

$(x-y)^3=x^3-3x^2y+3xy^2-y^3$


::: footer
:::

## SPECIAL PRODUCT {.smaller transition="fade-in fade-out"}

6. Square of a Trinomial

$(x+y+z)^2= x^2+y^2+z^2+2xy+2xz+2yz$


7.  Other Special Products

$(x+y)(x^2-xy+y^2)=x^3+y^3$ and 

$(x-y)(x^2+xy+y^2)=x^3-y^3$

::: footer
:::

## PRODUCT OF A MONOMIAL AND A POLYNOMIAL {.smaller transition="fade-in fade-out"}

Multiply the monomial by all terms of a polynomial

$$a(x+y)= ax+ay$$

**Example:**

1.  $$
    \begin{aligned}
    2x(3x+5y-z)&=2x(3x)+2x(5y)-2x(z) \\ 
    &= 6x^2+10xy-2xz
    \end{aligned}
    $$

2.  $x(2x+3y)=x(2x)+x(3y)=2x^2+ 3xy$

::: footer
:::

## PRODUCT OF THE SUM AND DIFFERENCE OF TWO TERMS {.smaller transition="fade-in fade-out"}

The product of the sum and difference of two terms is the difference of the squares of the terms.

$$(x+y)(x-y)=x^2-y^2$$

**Example:**

1.  $(3x+4y) (3x-4y)=(3x)^2-(4y)^2=9x^2-16y^2$
2.  $$\begin{align}(x+y-3)(x+y+3)&= [(x+y)-3][(x+y)+3] \\
&=(x+y)^2-(3)^2 \\
&= x^2+2xy+y^2-9
\end{align}$$

::: footer
:::

## SQUARE OF A BINOMIAL {.smaller transition="fade-in fade-out"}

The square of a binomial consists of the square of the first term; twice the product of the first and last terms; and the square of the last term.

$(x+y)^2=x^2+2xy+y^2$ and $(x-y)^2=x^2-2xy+y^2$

**Example:**

1.  $$\begin{aligned}(x-5)^2=(x)^2-2(x)(5)+(5)^2
&= x^2-10x+25\end{aligned}$$

2.  $$\begin{aligned}(3x+4y)^2= (3x)^2+2(3x)(4y)+(4y)^2
&= 3x^2+24xy+16y^2\end{aligned}$$

3.  $$\begin{aligned}(x-3y)=(x)^2-(2)(x)(3y)+(3y)^2= x^2-6xy+9y^2\end{aligned}$$

::: footer

:::

## PRODUCT OF TWO BINOMIAL {.smaller transition="fade-in fade-out"}

$$(x+a)(x+b)=x^2+(a+b)x+ab$$ and 

$$(ax+b)(cx+d)=acx^2+(ad+bc)x+bd$$


$\qquad$ To find the product of two binomials, you must multiply each factor of the first binomial by each factor of the second using the FOIL (First, Outer, Inner, and Last) method. 

::: footer
:::

## PRODUCT OF TWO BINOMIAL {.smaller transition="fade-in fade-out"}

**Example**

1. $$\begin{aligned}(x+5)(x-2)&=(x)^2+[(5-2)x+(5)(-2) \\
&= x^2+3x-10\end{aligned}$$

2. $$\begin{aligned}(2x+3)(4x+2)&=(2)(4)(x)^2+[(2)(2)+(3)(4)]x+(3)(2)\\
&= 8x^2+16x+6\end{aligned}$$

::: footer
:::

## CUBE OF A BINOMIAL {.smaller transition="fade-in fade-out"}

$$(x+y)^3=x^3+3x^2y+3xy^2+y^3$$

**Example:**

1.  $(2x+3y)^3$

a.  Find the cube of each term to get the first and the last terms. 

$$\qquad(2x)^3 = 8x^3, \qquad (3y)^3=27y^3$$

b.  The second term is three times the product of the square of the first term and the second term. 

$$3(2x)^2(3y)= 36x^2y$$

::: footer
:::

## CUBE OF A BINOMIAL {.smaller transition="fade-in fade-out"}

c.  The third term is three times the product of the first term and the square of the second term.

$$3(2x)(3y)^2= 54xy^2$$

Hence, $$(2x+3y)^3= 8x^3+36x^2y+54xy^2+27y^3$$

::: footer

:::

## CUBE OF A BINOMIAL {.smaller transition="fade-in fade-out"}

$$(x-y)^3=x^3-3x^2y+3xy^2-y^3$$

2.  $(4y-2z)^3$

a.  Find the cube of each term to get the first and the last terms. 
$$(4y)^3 = 64x^3, \qquad (-2z)^3= -8y^3$$

b.  The second term is three times the product of the square of the first term and the second term. 

$$3(4y)^2(-2z)= -96y^2z$$

::: footer

:::

## CUBE OF A BINOMIAL {.smaller transition="fade-in fade-out"}

c.  The third term is three times the product of the first term and the square of the second term. 

$$3(4y)(-2z)^2= 48yz^2$$

Hence, $$(4y-2z)^3$= $64x^3+-96y^2z+ 48yz^2-8y^3$$

::: footer

:::

## SQUARE OF A TRINOMIAL {.smaller transition="fade-in fade-out"}

$$(x+y+z)^2= x^2+y^2+z^2+2xy+2xz+2yz$$

**Example:**

1. $(2x+3y+2z)^2$

a. Find the sum of the squares of the first, second, and the last terms.

$$(2x)^2 = 4x^2, \qquad (3y)^2=9y^2, \qquad (2z)^2=4z^2$$

b. twice the product of the first and the second terms

$$ 2(2x)(3y)= 12xy$$

::: footer
:::

## SQUARE OF A TRINOMIAL {.smaller transition="fade-in fade-out"}

c. twice the product of the first and the last terms.
$$ 2(2x)(2z)=8xz$$

d. twice the product of the second and the last terms.
$$ 2(3y)(2z)=12yz$$

Hence, $$\ (2x+3y+2z)^2= 4x^2+9y^2+4z^2+12xy+8xz+12yz$$

::: footer
:::

## SQUARE OF A TRINOMIAL {.smaller transition="fade-in fade-out"}

$$(x-y-z)^2= x^2+y^2+z^2-2xy-2xz+2yz$$

**Example:**

1. $(4m-2n-z)^2$

a. Find the sum of the squares of the first, second, and the last terms.
$(4m)^2 = 16m^2, \qquad (-2n)^2=4n^2, \qquad (-z)^2=z^2$

b. twice the product of the first and the second terms
$\qquad 2(4m)(-2n)= -16mn$

c. twice the product of the first and the last terms.
$\qquad2(4m)(-z)= -8mz$

d. twice the product of the second and the last terms.
$\qquad 2(-2n)(-z)=4nz$

Hence, $(4m-2n-z)^2=16m^2+4n^2+z^2-16mn-8mz+4nz$

::: footer
11
:::

## PRODUCT OF THE SUM/ DIFFERENCE OF TWO CUBES {.smaller transition="fade-in fade-out"}

The sum or difference of two cubes can be factored into a product of a binomial times a trinomial.

A mnemonic for the signs of the factorization is the word "SOAP", the letters stand for "Same sign" as in the middle of the original expression, "Opposite sign", and "Always Positive".

That is, $x^3+y^3=(x+y)(x^2-xy+y^2)$ $x^3-y^3=(x-y)(x^2+xy+y^2)$

**Example:**

1.$$\begin{align} (x+2y)(x^2-2xy+4y^2)&= (x+2y)[(x)^2-x(2y)+(2y)^2)=(x)^3+(2y)^3= x^3+8y^3 \end {align}$$

2.$$\begin{align}(2x-3y)(4x^2+6xy+9y^2)&= (2x-3y)[(2x)^2+2x(3y)-(3y)^2)=(2x)^3-(3y)^3=2x^3-27y^3 \end {align}$$


